apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-tsm
  labels:
    apps.tanzu.vmware.com/workload-type: server 
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/has-tests-needs-workspace: "true"
    app.kubernetes.io/part-of: tap-hello-world
spec:
  env:
  - name: APP_MESSAGE
    value: tsm
  params:
  - name: gitops_ssh_secret
    value: gitlab-https
  - name: ports 
    value:
      - port: 80 
        containerPort: 8080 # modification
        name: http 
  source:
    git:
      url: http://gitlab.tap.h2o-2-19271.h2o.vmware.com/root/tap-hello-world.git
      ref:
        branch: main
