apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: tap-hello-world
spec:
  env:
  - name: APP_MESSAGE
    value: World
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/joostvdg/tap-hello-world.git
      ref:
        branch: main
