apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-ado
  labels:
    apps.tanzu.vmware.com/workload-type: server 
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/has-tests-needs-workspace: "true"
    app.kubernetes.io/part-of: tap-hello-world
spec:
  env:
  - name: APP_MESSAGE
    value: ado
  params:
  - name: gitops_ssh_secret
    value: azure-devops
  - name: ports 
    value:
      - port: 80 
        containerPort: 8080 # modification
        name: http 
  source:
    git:
      url: https://dev.azure.com/joostvandergriendt/my-first-repo/_git/my-first-repo
      ref:
        branch: main
